# config.yaml

general:
  prefix: MK-SPT-P045-1k
  rawdatadir: "/idia/projects/binary-smbhs/SPT/SPECTRAL_DOMAIN/LEON_TESTING/"
  output: output
  
  input_ms: "/idia/projects/binary-smbhs/SPT/SPECTRAL_DOMAIN/LEON_TESTING/"
  chan_div:
  total_chans: 1024
  npix: 8000
  cell_size: '1.7arcsec'
  chan_base_name:

wsclean:
  niter: 10000
  threshold: "0.1mJy"
  cellsize: "1arcsec"
  # Add any other WSClean parameters you need

fitstool:
  input_file: "data/processed/ms_file.ms"
  output_file: "results/final_cube.fits"
  # Add any other fitstool parameters you need

# Optional: general settings or paths
general:
  data_directory: "data/"
  results_directory: "results/"
  # Add any other general settings or paths
