paths:
  container_base_path: "/software/astro/caracal/STIMELA_IMAGES_1.7.5/"
  base_data_dir: "/path/to/base/data" # full path to ms file
  base_results_directory: "/path/to/base/results"
  wsclean_output_directory: "/path/to/wsclean/output"
  mstransform_output_directory: "/path/to/mstransform/output"
  wsclean_container: "stimela_wsclean_1.6.3.sif"
  kern_container: "/data/exp_soft/containers/kern6-2021-06-11.simg"
  casa_container: "stimela_casa_1.7.1.sif"
  log_file: "log_makeChanMaps.txt"

wsclean:
  local_rms: "MK-SPT-P045-1k.ms.contsub"
  memory: "95"
  weight: "briggs -0.5"
  niter: 1
  auto_threshold: 0.5
  auto_mask: 4
  gain: 0.1
  mgain: 0.95

mstransform:
  script: "mstransform_script.py"
  output_format: "fits"
  field_id: 0
  spw: "0"
  outframe: "LSRK"

general:
  total_numchans: 1024
  numchans: 100
  num_wsclean_runs: 10
  numpix: 6000
  pixscale: "1.7asec"
  chanbasename: "channelmap"
  cubebasename: "cube_MK-SPT-P045-1k.ms.contsub.fits"
  imfitorder: 4
  extensions_to_delete_r1:
  email_address:
    - "*-psf.fits"
    - "*-model.fits"
    - "*-residual.fits"
    - "*-dirty.fits"
    - "-MFS-*.fits"
  extensions_to_delete_r2:
    - "*.linefile"
    - "*.contfile"
    - "*-image.fits"
